receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    send_batch_size: 10
    timeout: 1s
  memory_limiter:
    limit_mib: 100
    spike_limit_mib: 20
    check_interval: 1s

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "csv_metrics"
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [prometheus] 