global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 3s

scrape_configs:
  - job_name: 'otel-metrics'
    static_configs:
      - targets: ['otel-collector:8889']
    metrics_path: '/metrics'